### ISSUE TITLE
Error Installation in Rails 5 

### ISSUE THREAD

**Issue by ronnierios** [mldoscar/bcn_ni#4]
Hey Bro,

I'm trying to install the gem in both ways

`gem 'bcn_ni', git: 'https://github.com/mldoscar/bcn_ni', branch: 'master'`
`gem 'bcn_ni', '>= 0.1.4'`

But I got the following  error, I am using `'rails', '~> 5.1.5'`

![image](https://user-images.githubusercontent.com/5624647/58450539-8c79ff80-80cc-11e9-88b3-5ab20b1d383e.png)

Any idea to resolve? Thanks in advance

**Comment by mldoscar** [comment]
Try to rebuild your Gemfile.lock

Delete `Gemfile.lock` file and execute `bundle install again`

Let me know how that work for you,
Regards

**Comment by ronnierios** [comment]
The gem does not work with rails ```5.1.5``` so upgraded to `5.2.3`

Now it works smoothly in scrapping mode

Thanks Oscar
